let stockProductos = [
    {id: 1,
        nombre: "Nikon", 
        tipo: "camera", 
        cantidad: 1, 
        precio: 1280, 
        img: './img/gift-habeshaw-JlaHTZ_Rp7M-unsplash.jpg'},
    {id: 2, 
         nombre: "Canon",
         tipo: "camera", 
         cantidad: 1, 
         precio: 2100, 
         img: './img/manik-roy-94l7pPFLasA-unsplash.jpg'},
    {id: 3, 
         nombre: "Fujifilm", 
         tipo: "camera", 
         cantidad: 1,
         precio: 3200,
         img: './img/rohan-gangopadhyay-rtteWkqGV6k-unsplash.jpg'},
    {id: 4, 
         nombre: "Sony I", 
         tipo: "camerao", 
         cantidad: 1,  
         precio: 1400, 
         img: './img/brent-ninaber-6qesnUQceJA-unsplash.jpg'},
    {id: 5, 
         nombre: "Sony II", 
         tipo: "camera", 
         cantidad: 1, 
         precio: 1200, 
         img: './img/dennis-klein-vTQMGidHrTE-unsplash.jpg'},
    {id: 6, 
         nombre: "Nikon I", 
         tipo: "camera", 
         cantidad: 1,  
         precio: 3500, 
         img: './img/mikkel-bech-Rux50ySjahc-unsplash.jpg'},
    {id: 7, 
         nombre: "Canon I", 
         tipo: "camera", 
         cantidad: 1, 
         precio: 4500,
         img: './img/oscar-ivan-esquivel-arteaga-_XE2Iytnf_M-unsplash.jpg'},
    {id: 8, 
         nombre: "Nikon II", 
         tipo: "camera", 
         cantidad: 1, 
         precio: 2300, 
         img: './img/milad-fakurian-J379XzX_DZo-unsplash.jpg'},
    {id: 9, 
         nombre: "Camera Len 1", 
         tipo: "lens", 
         cantidad: 1, 
         precio: 500, 
         img: './img/isabella-mendes-lRgkUlxJCkA-unsplash.jpg'},
    {id: 10, 
         nombre: "Camera Len 2", 
         tipo: "lens", 
         cantidad: 1,
         precio: 700, 
         img: './img/zac-wolff-ZqHvJFfC75Y-unsplash.jpg'},
    {id: 11, 
         nombre: "Camera Len 3", 
         tipo: "lens", 
         cantidad: 1,
         precio: 700,
         img: './img/braxton-apana-38bisq-Fngg-unsplash.jpg'},
    {id: 12, 
         nombre: "Camera Len 4",
         tipo: "lens", 
         cantidad: 1, 
         precio: 700, 
         img: './img/ahmad-mohammed-KrRDIeJILVk-unsplash.jpg'},
    {id: 13,
         nombre: "Lights", 
         tipo: "accesories", 
         cantidad: 1, 
         precio: 900, 
         img: './img/aditya-wardhana-S6OSYUlvJxo-unsplash.jpg'},
    {id: 14,
         nombre: "Bag", 
         tipo: "accesories", 
         cantidad: 1, 
         precio: 900, 
         img: './img/sj-eX0N1Ex-qFo-unsplash.jpg'}, 
    {id: 15,
         nombre: "Filter", 
         tipo: "accesories", 
         cantidad: 1, 
         precio: 900, 
         img: './img/chris-yang-8M8YT8iz_oY-unsplash.jpg'},
    {id: 16,
         nombre: "Kit", 
         tipo: "accesories", 
         cantidad: 1, 
         precio: 3920, 
         img: './img/screen-post-T1JPOK-Zz_8-unsplash.jpg'},
]